### ISSUE TITLE
CEH v12

### ISSUE THREAD

**Issue by edake** [hopan/ceh_feedback#2]
Multi-answer questions are always evaluated as incorrect.

In the TRUE/FALSE question, you can only select TRUE and the answer is FALSE, so it always evaluates it as incorrect.

There are also several answers that are not correct according to the CEH syllabus.

**Comment by hopan** [comment]
Thanks @edake !

I've just fix the multiple-choice questions. The TRUE/FALSE questions are working well.
There are also several answers that are not correct according to the CEH syllabus => Please provide the details. Thankyou!
