### ISSUE TITLE
CEHv11

### ISSUE THREAD

**Issue by vmcj** [hopan/ceh_feedback#3]
For the question:
_If you want only to scan fewer ports than the default scan using Nmap tool, which option would you use?_

I think the correct answer should be `-F` not `-P`, see:

```
-F (fast)
By default, Nmap scans the 1,000 most popular ports of each protocol it is asked to scan. Alternatively, you can specify the -F (fast) option to scan only the 100 most common ports in each protocol or --top-ports to specify an arbitrary number of ports to scan.
```

**Comment by hopan** [comment]
Thankyou @vmcj. Just updated the question.
